global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'qr-queue-backend'
    static_configs:
      - targets: ['qr-queue-backend:3000']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

# remote_write:
#   - url: ${PROMETHEUS_URL}
#     basic_auth:
#       username: ${PROMETHEUS_USERNAME}
#       password: ${PROMETHEUS_PASSWORD}
